<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0IhExb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0IhExb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0IhExb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0IhExb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX0IhExb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X0IhExb',
    'container.build_id' => '3e7f13f9',
    'container.build_time' => 1524613475,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0IhExb');
