<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container22M0gFW\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container22M0gFW/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container22M0gFW.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container22M0gFW\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container22M0gFW\srcDevDebugProjectContainer(array(
    'container.build_hash' => '22M0gFW',
    'container.build_id' => '515634b5',
    'container.build_time' => 1524611432,
), __DIR__.\DIRECTORY_SEPARATOR.'Container22M0gFW');
