<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFP1ZDUm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFP1ZDUm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFP1ZDUm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFP1ZDUm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFP1ZDUm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FP1ZDUm',
    'container.build_id' => 'd8838c41',
    'container.build_time' => 1524691985,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFP1ZDUm');
